import { Seller, Listing } from '../../lib/types'

export const MOCK_SELLERS: Seller[] = [
  {
    id: 's1',
    name: 'Ernesto Bacolod',
    shopName: 'Bacolod Poultry Farm',
    location: 'Pavia, Iloilo',
    city: 'Pavia',
    province: 'Iloilo',
    isVerified: true,
    tier: 'premium',
    rating: 4.9,
    reviewCount: 132,
    listingCount: 12,
    memberSinceYears: 3,
    joinedAt: new Date('2021-03-10'),
  },
  {
    id: 's2',
    name: 'Felisa Ranario',
    shopName: "Felisa's Native Poultry",
    location: 'Sta. Barbara, Iloilo',
    city: 'Sta. Barbara',
    province: 'Iloilo',
    isVerified: true,
    tier: 'standard',
    rating: 4.7,
    reviewCount: 89,
    listingCount: 7,
    memberSinceYears: 2,
    joinedAt: new Date('2022-06-15'),
  },
  {
    id: 's3',
    name: 'Ramon Dela Cruz',
    shopName: 'RC Poultry Supply',
    location: 'Roxas City, Capiz',
    city: 'Roxas City',
    province: 'Capiz',
    isVerified: true,
    tier: 'premium',
    rating: 4.8,
    reviewCount: 211,
    listingCount: 18,
    memberSinceYears: 5,
    joinedAt: new Date('2019-01-20'),
  },
  {
    id: 's4',
    name: 'Maria Santos',
    shopName: 'Santos Farm Fresh',
    location: 'Kalibo, Aklan',
    city: 'Kalibo',
    province: 'Aklan',
    isVerified: false,
    tier: 'standard',
    rating: 4.3,
    reviewCount: 34,
    listingCount: 5,
    memberSinceYears: 1,
    joinedAt: new Date('2023-08-01'),
  },
]

export const MOCK_LISTINGS: Listing[] = [
  {
    id: 'l1',
    sellerId: 's1',
    seller: MOCK_SELLERS[0],
    title: 'Live Broiler Chicken',
    category: 'buhay_na_manok',
    description: '5-6 weeks old, ~2.5kg avg. Ready for harvest.',
    price: 185,
    priceUnit: 'kilo',
    stock: 500,
    stockUnit: 'heads',
    isFeatured: true,
    images: [],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'l2',
    sellerId: 's1',
    seller: MOCK_SELLERS[0],
    title: 'Broiler Starter 50kg',
    category: 'feeds',
    description: 'Brand: FarmBest. Bag sealed and fresh.',
    price: 1250,
    priceUnit: 'bag',
    stock: 80,
    stockUnit: 'bags',
    isFeatured: false,
    images: [],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'l3',
    sellerId: 's2',
    seller: MOCK_SELLERS[1],
    title: 'Native Manok (Bisaya)',
    category: 'buhay_na_manok',
    description: 'Free-range native chicken, 3-4 months old.',
    price: 280,
    priceUnit: 'kilo',
    stock: 120,
    stockUnit: 'heads',
    isFeatured: true,
    images: [],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'l4',
    sellerId: 's3',
    seller: MOCK_SELLERS[2],
    title: 'Native Itlog (Trays)',
    category: 'itlog',
    description: '30 pcs per tray. Fresh, collected daily.',
    price: 220,
    priceUnit: 'tray',
    stock: 60,
    stockUnit: 'trays',
    isFeatured: false,
    images: [],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'l5',
    sellerId: 's3',
    seller: MOCK_SELLERS[2],
    title: 'Chicken Vitamins (Roboran H)',
    category: 'gamot_bitamina',
    description: 'Vitamin supplement for layers and broilers.',
    price: 450,
    priceUnit: 'pack',
    stock: 200,
    stockUnit: 'packs',
    isFeatured: false,
    images: [],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'l6',
    sellerId: 's4',
    seller: MOCK_SELLERS[3],
    title: 'Layer Chicken (Pullet)',
    category: 'buhay_na_manok',
    description: '16-18 weeks old pullets, ready to lay in 2-4 weeks.',
    price: 320,
    priceUnit: 'head',
    stock: 80,
    stockUnit: 'heads',
    isFeatured: false,
    images: [],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
]

export const CATEGORIES = [
  { value: 'buhay_na_manok', label: 'Buhay na Manok' },
  { value: 'feeds', label: 'Feeds (Sako)' },
  { value: 'itlog', label: 'Itlog' },
  { value: 'gamot_bitamina', label: 'Gamot / Bitamina' },
  { value: 'supplies', label: 'Supplies' },
] as const

export const CITIES = [
  'Iloilo City', 'Pavia', 'Sta. Barbara', 'Roxas City', 'Kalibo', 'Bacolod'
]

export const SORT_OPTIONS = [
  { value: 'popular', label: 'Pinaka-Popular' },
  { value: 'newest', label: 'Pinakabago' },
  { value: 'price_asc', label: 'Presyo: Mababaw' },
  { value: 'price_desc', label: 'Presyo: Mataas' },
  { value: 'rating', label: 'Pinaka-mataas Rating' },
] as const